### PR TITLE
Add eslint plugin for automated syntax checks

### PR DESCRIPTION
**Pull request by mens-rea**
- Add eslint for automated syntax checks
- Fix lint errors related to prop validation

### CODE REVIEW

**Review by extrajavarice — APPROVED** [review]

**Review by extrajavarice — COMMENTED** [review]
Hi Sir JM, I cannot approve this changes, my first reason is you deleted my personal token to connect the project to firebase, second reason is you deleted so many function that is important. Thank you.

**Comment by mens-rea** [comment]
> Hi Sir JM, I cannot approve this changes, my first reason is you deleted my personal token to connect the project to firebase, second reason is you deleted so many function that is important. Thank you.

I did not remove any credentials for this PR. I also did not delete any important functions.

**Review by extrajavarice — APPROVED** [review]

**Comment by extrajavarice** [comment]
> > Hi Sir JM, I cannot approve this changes, my first reason is you deleted my personal token to connect the project to firebase, second reason is you deleted so many function that is important. Thank you.
> 
> I did not remove any credentials for this PR. I also did not delete any important functions.

yea yea sorry sir, mali lang ng tingin !

**Review by extrajavarice — CHANGES_REQUESTED** [review]
I cant approve this PR because it has different function added that is not related eslint

**Pull request closed without merging**
